"""Turns the name into per-letter SVG outlines for the 3D hero.

Run: python3 tools/build_name_path.py
Uses fontTools (opentype.js produced NaN coordinates for some DM Serif Display glyphs).
"""
import json
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

NAME = "Lavanya"
SIZE = 200
HERE = Path(__file__).parent
font = TTFont(HERE / "DMSerifDisplay-Regular.ttf")
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
scale = SIZE / font["head"].unitsPerEm

paths, x = [], 0.0
xmin = ymin = float("inf")
xmax = ymax = float("-inf")
prev = None
kern = font["kern"].kernTables[0].kernTable if "kern" in font else {}
for ch in NAME:
    name = cmap[ord(ch)]
    if prev and (prev, name) in kern:
        x += kern[(prev, name)] * scale
    # Font y runs up; SVG y runs down. Flip here so the viewer can treat it like any SVG.
    t = (scale, 0, 0, -scale, x, 0)
    svg = SVGPathPen(glyphs)
    glyphs[name].draw(TransformPen(svg, t))
    paths.append(svg.getCommands())
    b = BoundsPen(glyphs)
    glyphs[name].draw(TransformPen(b, t))
    if b.bounds:
        xmin, ymin = min(xmin, b.bounds[0]), min(ymin, b.bounds[1])
        xmax, ymax = max(xmax, b.bounds[2]), max(ymax, b.bounds[3])
    x += glyphs[name].width * scale
    prev = name

assert not any("nan" in p.lower() for p in paths), "NaN in outline"
box = {"x": round(xmin, 2), "y": round(ymin, 2), "w": round(xmax - xmin, 2), "h": round(ymax - ymin, 2)}
out = HERE.parent / "src" / "data" / "namePath.ts"
out.write_text(
    "// Generated by tools/build_name_path.py from DM Serif Display. Do not edit by hand.\n"
    f"export const NAME_PATHS: string[] = {json.dumps(paths)};\n"
    f"export const NAME_BOX = {json.dumps(box)};\n"
)
print("letters", len(paths), "box", box)
